### PR TITLE
fix: Add missing loadTUI function for no-argument invocation

### LINKED ISSUE #1589: Running task-master with no arguments throws 'loadTUI is not defined' error
## Problem Statement

Running `task-master` with no arguments throws a ReferenceError instead of showing help or launching the TUI.

## Current Behavior

```bash
$ task-master
Error: loadTUI is not defined
```

Exit code: 1

## Expected Behavior

One of:
1. Launch TUI if `@tm/tui` package is installed
2. Fall back gracefully to showing help if TUI is not available

## Root Cause

In `scripts/modules/commands.js`, the `launchREPL()` function (lines ~5255-5258) calls `loadTUI()`:

```javascript
async function launchREPL() {
    const React = await import('react');
    const tui = await loadTUI();  // ❌ loadTUI is never defined
    
    if (!tui) {
        // Fallback to help if TUI not available
        console.log(chalk.yellow('TUI mode not available. Install @tm/tui to enable.'));
        // ... shows help instead
    }
}
```

The `loadTUI()` function is:
- Called but never imported at the top of the file
- Not defined anywhere in commands.js
- Not exported from any module

## Flow

```
task-master (no args)
    → index.js spawns dev.js
    → dev.js → runCLI(process.argv)
    → commands.js → runCLI() checks argv.length <= 2
    → launchREPL() called
    → loadTUI() called → ❌ ReferenceError
```

## Suggested Fix

Define the `loadTUI()` function to dynamically import `@tm/tui`:

```javascript
async function loadTUI() {
    try {
        const tuiModule = await import('@tm/tui');
        return tuiModule;
    } catch (error) {
        return null; // TUI not available
    }
}
```

This allows the existing fallback logic (lines 5259-5270) to work correctly and show help when TUI is not installed.

## Impact

- Users cannot run `task-master` without arguments
- The intended TUI experience is broken
- The graceful fallback to help is not functioning

### PR DESCRIPTION
**Pull request by bjcoombs**
## Summary

- Adds the missing `loadTUI()` function that was being called but never defined
- Running `task-master` with no arguments now gracefully falls back to showing help instead of throwing an error

## Changes Made

Added `loadTUI()` function in `scripts/modules/commands.js` that:
- Dynamically imports `@tm/tui` package
- Returns null if the package is not installed
- Allows existing fallback logic to display help when TUI is unavailable

## Test Plan

- [x] Run `task-master` with no arguments - should show "TUI mode not available" message and display help
- [x] Build succeeds

Fixes #1589

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved handling when the TUI is unavailable: shows a "TUI coming soon" message, displays contextual or general help as appropriate, and exits gracefully instead of attempting initialization.
  * Interactive TUI behavior remains unchanged when the TUI module is present.

* **Release Notes**
  * Added 0.42.0 release notes section.

* **Chores**
  * Bumped package version to 0.42.0 and removed several draft changelog entries.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: scripts/modules/commands.js [hunk 1]
```diff
@@ -5249,6 +5249,20 @@ Examples:
...
+ */
+async function loadTUI() {
+	try {
+		const tuiModule = await import('@tm/tui');
+		return tuiModule;
+	} catch (error) {
+		// TUI package not installed
+		return null;
+	}
+}
```
Comment (Crunchyman-ralph) [inline scripts/modules/commands.js:5259]: nope, just return "coming soon" or something. We're going to launch tui soon, but this was a mistake, so we need to gracefully handle it, maybe with a help.

Also, no need for dynamic imports, just do a normal import, but in this case, @tm/tui doesn't exist, it will soon though!

Comment (bjcoombs) [reply scripts/modules/commands.js:5259]: Done! Simplified to just return null with "TUI coming soon" message. No dynamic imports.

**Comment by Crunchyman-ralph** [comment]
@bjcoombs can you rebase, I'll merge this as soon as you rebase!

**Comment by bjcoombs** [comment]
Rebased and squashed into a single commit. Ready to merge!

**Comment by Crunchyman-ralph** [comment]
@bjcoombs seems like your rebase didn't work, I went ahead and took care of it, as soon as CI finishes, I'll merge this
