### PR TITLE
fix: Critical writeJSON Context Fixes - Prevent Tag Corruption

### LINKED ISSUE #904: bug: `remove_subtask` deletes all tags other than `master` as well as tasks
### Description

The `remove_subtask` command (both MCP tool `remove_subtask` and CLI `task-master remove-subtask`) deletes all tags other than `master` as well as all tasks outside the current tag so that the file now holds only the tasks from the tag used previously under the `master` tag.

### Steps to Reproduce

1. Initialize a TaskMaster project with tagged structure containing multiple tags:
   ```bash
   task-master init
   task-master add-tag feature-web-interface
   task-master add-tag test-tag
   ```
2. Verify the tagged structure is intact:
   ```bash
   task-master tags
   ```
3. Add some tasks and subtasks:
   ```bash
   task-master use-tag test-tag
   task-master add-task --prompt="Test parent task"
   task-master add-subtask --parent=1 --title="Test subtask"
   ```
4. Execute the remove_subtask command:
   ```bash
   task-master remove-subtask --id=1.1
   ```
5. Check the tasks.json file and tag structure after execution:
   ```bash
   task-master tags
   task-master list
   ```

### Expected Behavior

- The command should remove only the specified subtask from its parent task
- The tagged structure should be preserved with all tags and metadata intact
- Only the target subtask should be affected
- All other tags and tasks should remain untouched
- The JSON file should maintain proper structure and remain parseable

### Actual Behavior

- The entire tag system is destroyed
- All tag metadata is lost
- The tagged file structure is corrupted or converted to an incompatible format
- Tasks from all tags become inaccessible

### Screenshots or Logs

Before execution: Properly structured tagged format with multiple tags and metadata
After execution: Corrupted file with complete loss of tag structure

### Environment

- Task Master version: 18.0 (latest stable)
- Node.js version: 22.14
- Operating system: macOS (also affects Linux)
- IDE: Cursor with MCP integration, also affects CLI usage

### Additional Context

Possibly related to #902 
I've noticed the same thing happens with other commands - `expend_task`, and even `add_task/subtask`, but didn't drill deeper into it

### PR DESCRIPTION
**Pull request by mm-parthy**
Fix critical bug where task operations in one tag context would corrupt or delete tasks from other tags in tasks.json. The root cause was missing `projectRoot` and `tag` parameters in `writeJSON` calls across multiple functions including fix-dependencies, expand-task, set-task-status, add-task, remove-task, add-subtask, and tag-management operations.

This resolves user-reported issues where tasks would mysteriously disappear after performing operations in multi-tag environments.

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Testing

- [x] I have tested this locally
- [x] All existing tests pass
- [x] I have added tests for new functionality

## Changeset

- [x] I have created a changeset (or this change doesn't need one)

## Additional Notes

This is a critical data corruption bug that causes silent task deletion in tagged task environments. 

closes #904 #902 

Key fixes:
- Updated `fixDependenciesDirect` and related MCP tools to include context parameters
- Fixed `expandTaskDirect` writeJSON calls to preserve tag context
- Enhanced tag management operations (`createTag`, `deleteTag`, `renameTag`, `copyTag`) with proper context
- Added `tag` parameter support to `setTaskStatusDirect` 
- Fixed `addTask`, `removeTask`, and `addSubtask` functions to use current tag context
- Added comprehensive unit tests to prevent regression

### CODE REVIEW

File: scripts/modules/task-manager/remove-task.js [hunk 1]
```diff
@@ -1,7 +1,6 @@
-import fs from 'fs';
 import path from 'path';
-
-import { log, readJSON, writeJSON } from '../utils.js';
+import * as fs from 'fs';
```
Comment (Crunchyman-ralph) [inline scripts/modules/task-manager/remove-task.js:2]:
```suggestion
import fs from 'fs';
```

**Comment by zbeyens** [comment]
Got all my tags deleted 🥲 Would love to get this released asap :)

**Comment by amir-stadler-ludeo** [comment]
@Crunchyman-ralph @eyaltoledano any reason not to release this fix as a patch version?
